GradAcademyCSharp/GradAcademyCSharp/Controllers/PaidInvoiceController.cs
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using GradAcademyCSharp.Models;
using GradAcademyCSharp.Service.Contracts;

namespace GradAcademyCSharp.Controllers
{
    public class PaidInvoiceController : Controller
    {
        private readonly IPaymentService _paymentService;

        public PaidInvoiceController(IPaymentService paymentService)
        {
            _paymentService = paymentService;
        }

        // GET: PaidInvoice
        public ActionResult Index(int id)
        {
            var paidInvoices = _paymentService.GetClosedInvoices(id).Select(Mapper.Map<PaidInvoiceModel>);

            return View(paidInvoices);
        }
    }
}

GradAcademyCSharp/GradAcademyCSharp/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using GradAcademyCSharp.BusinessObjects;
using GradAcademyCSharp.Models;
using GradAcademyCSharp.Service.Contracts;

namespace GradAcademyCSharp.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IPaymentService _paymentService;
        private readonly IWorkerService _workerService;

        private const int MAX_NUMBER_OF_CHECKS = 10;

        public PaymentController(IPaymentService paymentService, IWorkerService workerService)
        {
            _paymentService = paymentService;
            _workerService = workerService;
        }

        //GET
        public ActionResult Index(int id)
        {
            var workableChecks = _workerService.GetOpenWorkerChecks(id).Select(Mapper.Map<CheckModel>);
            var worker = SetWorkerStatistics(Mapper.Map<WorkerModel>(_workerService.GetWorker(id)));

            return View(new WorkerCheckModel
            {
                Worker = worker,
                WorkableChecks = workableChecks
            });
        }

        //GET
        public ActionResult Edit(int checkId)
        {
            var check = _paymentService.GetCheck(checkId);
            var clientInvoices = _paymentService.GetOpenInvoices(check.ClientId)
                .OrderBy(x => x.DueDate)
                .Select(Mapper.Map<Invoice, InvoiceModel>)
                .ToList();

            var viewModel = new PaymentModel()
            {
                Check = Mapper.Map<Check, CheckModel>(check),
                ClientInvoices = clientInvoices
            };

            return View(viewModel);
        }

        //POST
        [HttpPost]
        public ActionResult Edit(int checkId, List<InvoiceModel> invoices)
        {
            var check = Mapper.Map<CheckModel>(_paymentService.GetCheck(checkId));
            invoices = invoices.Where(x => x.Scheduled).OrderBy(x => x.DueDate).ToList();

            var paidInvoices = new List<PaidInvoiceModel>();

            foreach (var clientInvoice in invoices)
            {
                if (check.Amount == 0) break;

                var paymentAmount = _paymentService.SchedulePayment(checkId, clientInvoice.Id);
                if (paymentAmount == 0) continue;

                check.Amount -= paymentAmount;
                var paidInvoice = _paymentService.GetInvoice(clientInvoice.Id);

                paidInvoices.Add(new PaidInvoiceModel()
                {
                    InvoiceId = paidInvoice.Id,
                    AmountDueBefore =  paidInvoice.AmountDue + paymentAmount,
                    CompletedDate = DateTime.Now,
                    DueDate = paidInvoice.DueDate,
                    AmountPaid = paymentAmount
                });
            }

            return View("PaymentConfirmation", paidInvoices);
        }

        public ActionResult AddItems(int id)
        {
            var workerChecks = _workerService.GetOpenWorkerChecks(id).ToList();
            var newCheckCount = MAX_NUMBER_OF_CHECKS - workerChecks.Count();

            var newWorkerChecks = _workerService.GetMoreWorkerChecks(newCheckCount, id).ToList();
            workerChecks.AddRange(newWorkerChecks);

            var workableChecks = new List<CheckModel>();
            foreach (var workerCheck in workerChecks)
            {
                if (!workerCheck.AssignedWorker.HasValue)
                    continue;

                var checkModel = Mapper.Map<CheckModel>(workerCheck);

                workableChecks.Add(checkModel);
            }

            var worker = SetWorkerStatistics(Mapper.Map<WorkerModel>(_workerService.GetWorker(id)));

            return View("Index", new WorkerCheckModel
            {
                Worker = worker,
                WorkableChecks = workableChecks
            });
        }

        private WorkerModel SetWorkerStatistics(WorkerModel worker)
        {
            if (worker != null)
            {
                worker.AverageCompletionTime = _workerService.GetAverageCheckCompletionTime(worker.Id);
                worker.NumChecksCompleteInLastSevenDays = _workerService.GetNumberOfChecksCompleted(worker.Id, new TimeSpan(7, 0, 0, 0));
            }

            return worker;
        }

        public ActionResult BackToChecks()
        {
            var worker = _workerService.GetByEmail(User.Identity.Name);
            if (worker != null)
            {
                return RedirectToAction("Index", new { id = worker.Id });
            }

            return RedirectToAction("Login", "Home");
        }
    }
}

GradAcademyCSharp/GradAcademyCSharp/Views/Payment/Edit.cshtml
@model GradAcademyCSharp.Models.PaymentModel

@{
    ViewBag.Title = "Edit";
}

<h2>Apply Check to Invoices</h2>
<hr />

<div>
    <h3>Amount Remaining: @Html.DisplayFor(model => model.Check.Amount)</h3>

    Schedule payment for one or more invoices up the sum total of the check.<br/>
    NOTE: The check will be applied to invoices with earlier due dates first.
</div>
<br />

@using (Html.BeginForm(new {checkId = Model.Check.Id}))
{
    @Html.AntiForgeryToken()
    
    <fieldset>
        @Html.Partial("_InvoicesEditPartial", Model.ClientInvoices.ToList())
    </fieldset>

    <input type="submit" value="Save" class="btn btn-primary"/>
    if (Model.Check.AssignedWorker.HasValue)
    {
        @Html.ActionLink("Back to Checks", "Index", "Payment", new { id = Model.Check.AssignedWorker.Value }, new { @class = "btn btn-primary" })
    }

}

GradAcademyCSharp/GradAcademyCSharp/Views/Payment/Index.cshtml
@model GradAcademyCSharp.Models.WorkerCheckModel

@{
    ViewBag.Title = "Your Queue";
}

<h2>Your Queue</h2>
<br/>
<div>
    @Html.LabelFor(model => model.Worker.AverageCompletionTime)
    @Html.DisplayFor(model => model.Worker.AverageCompletionTime)
</div>
<div>
    @Html.LabelFor(model => model.Worker.NumChecksCompleteInLastSevenDays)
    @Html.DisplayFor(model => model.Worker.NumChecksCompleteInLastSevenDays)
</div>
Use the Schedule Payment link to assign the selected check to one (or more) invoices.
<hr/>



<div>
    @Html.ActionLink("Add more checks", "AddItems", new { id = Model.Worker.Id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Paid invoices", "Index", "PaidInvoice", new {id = Model.Worker.Id}, new {@class = "btn btn-primary"})
</div>
<br/>

<div class="row">
    @if (Model.WorkableChecks.Any())
    {
        @Html.Partial("_WorkableChecksPartial", Model.WorkableChecks)
    }
</div>

   

GradAcademyCSharp/GradAcademyCSharp/Views/Payment/PaymentConfirmation.cshtml
@model IEnumerable<GradAcademyCSharp.Models.PaidInvoiceModel>

@{
    ViewBag.Title = "PaymentConfirmation";
}

<h2>Payment Confirmation</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.InvoiceId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AmountDueBefore)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AmountPaid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AmountDueAfter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
    </tr>

    @foreach (var invoice in Model)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => invoice.InvoiceId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => invoice.AmountDueBefore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => invoice.AmountPaid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => invoice.AmountDueAfter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => invoice.DueDate)
            </td>
        </tr>
    }
</table>
<div>
    @Html.ActionLink("Back to checks", "BackToChecks")
</div>

GradAcademyCSharp/GradAcademyCSharp/Views/Payment/_InvoicesEditPartial.cshtml
@model List<GradAcademyCSharp.Models.InvoiceModel>

@if (Model.Any())
{
    <table class="table" id="PaymentInvoiceTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => Model[0].Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].TotalAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].AmountDue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].DueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Scheduled)
        </th>
    </tr>

    @for (var i = 0; i < Model.Count(); i++)
    {
    @Html.HiddenFor(modelItem => Model[i].Id)
    @Html.HiddenFor(modelItem => Model[i].ClientId)

    <tr>
        <td>
            @Html.HiddenFor(modelItem => Model[i].Id)
            @Html.DisplayFor(modelItem => Model[i].Id)
        </td>
        <td>
            @Html.HiddenFor(modelItem => Model[i].TotalAmount)
            @Html.DisplayFor(modelItem => Model[i].TotalAmount)
        </td>
        <td>
            @Html.HiddenFor(modelItem => Model[i].AmountDue)
            @Html.DisplayFor(modelItem => Model[i].AmountDue)
        </td>
        <td>
            @Html.HiddenFor(modelItem => Model[i].DueDate)
            @Html.DisplayFor(modelItem => Model[i].DueDate)
        </td>
        <td>
            @Html.EditorFor(modelItem => Model[i].Scheduled)
        </td>
    </tr>
    }
</table>
    
}

GradAcademyCSharp/GradAcademyCSharp/Views/Payment/_WorkableChecksPartial.cshtml
@model IEnumerable<GradAcademyCSharp.Models.CheckModel>

<div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CheckNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ClientName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(model => item.CheckNumber)
                </td>
                <td>
                    @Html.DisplayFor(model => item.StartDate)
                </td>
                <td>
                    @Html.ActionLink("Schedule Payment", "Edit", new { checkId = item.Id }, null)
                </td>
            </tr>
        }
    </table>
</div>